#!/bin/bash



t="$(make 2>&1)"
# echo $t

watchexec --exts hs 't="$(make 2>&1)"; printf "\033c"; printf "%s" "$t"; echo "\`\`\`\n""$t""\n\`\`\`"> README.md'


# fswatch -o --event Updated --event Created -e ".*" -i ".*\\.hs$" . \
#   | xargs -I{} sh -c 't="$(make 2>&1)"; echo "[2J[H$t"'
